### ISSUE TITLE
Add padding below the Contact Us button

### ISSUE THREAD

**Issue by jearjujaroen** [womenbuildweb3/official-website#20]
<img width="451" alt="image" src="https://user-images.githubusercontent.com/6855463/162525222-56cb21de-074d-4d9e-b9ab-ed10b610b594.png">

**Comment by qgarcia95** [comment]
@jearjujaroen Hello, how are you I was wondering if I can get this issue assigned? I need to contribute to an open source project and have my code reviewed by a human and merged successfully as part of the assignment criteria. This is due in the next few days so I would greatly appreciate a response as soon as you get a chance, thank you have a good day.

**Comment by qgarcia95** [comment]
@jearjujaroen @amoweolubusayo can I get this assigned?, I am going to start working on this issue. I will submit a commit of my branch on the issue and open a pull request upon completion.

**Comment by jearjujaroen** [comment]
@qgarcia95 yes, you can go ahead and take this issue. Thanks for your contribution!

**Comment by qgarcia95** [comment]
![Capture](https://user-images.githubusercontent.com/79949335/163019732-b70d09df-9138-4571-bee0-43691c877b43.JPG)

@jearjujaroen @amoweolubusayo Hello, I think this should fix this issue. I opened a pull request to close this issue, it has my code changes and a comment explaining what was done. Here is a screenshot as well. If anything else needs to be addressed on my end please let me know. This assignment is due tonight and I need to get this reviewed and successfully merged as soon as possible. Thank you have a wonderful day.

**Comment by amoweolubusayo** [comment]
Hello @qgarcia95. Thank you for contributing… We actually intend to make our stack uniform. So, there’s an agreement to use tailwind css as opposed to normal css.

**Comment by qgarcia95** [comment]
@amoweolubusayo Understandable, I reverted it back to tailwind and fixed the padding on button. Is this okay? What else is needed, I committed those changes to my initial pull request, if you look there you can see the changes under the commits.

**Comment by qgarcia95** [comment]
@amoweolubusayo @jearjujaroen  should I open up a new pull request with only the one commit? Not sure on the protocol here, new to open source contributing

**Comment by amoweolubusayo** [comment]
Good one! Issue has been resolved.
